[package]
name = "ligeia"
version = "0.1.0"
edition = "2024"

[dependencies]
eisheth = { path = "../eisheth/" }
lalrpop-util = { version = "0.22.2", features = ["unicode", "lexer"] }
libc = "0.2.174"
paste = "1.0.15"

[lints]
workspace = true

[build-dependencies]
lalrpop = "0.22.2"
