[package]
name = "ligeia-compiler-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
eisheth = { path = "../eisheth/" }
lalrpop-util = { version = "0.22.2", features = ["unicode", "lexer"] }
thiserror = "2.0.12"

[build-dependencies]
lalrpop = "0.22.2"

[lints]
workspace = true
